- name: New Instance Installation
  hosts: "{{ hostname }}"
  become: true
  vars:
    - var_node: /tmp
    - homeDir: /home/{{ user }}
    - appDir : app
  roles:
    - node
  tasks:
  - name: Create APP Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  - name: Copy app
    synchronize:
      src: ../app
      dest: "{{ homeDir }}"
      verify_host: no
      rsync_opts:
        - "--exclude=node_module"

  - name: Running NPM install
    npm: path={{ homeDir }}/{{ appDir }}
    register: npm_finished

  - name: App launch
    command: pm2 start index.js --name app chdir={{homeDir}}/{{appDir}}
    when: npm_finished.changed
